version: '2.1'

services:
  app:
    build: .
    restart: unless-stopped
    command: sh -c "cd dist && http-server -p 3000 -a 0.0.0.0"
    ports:
      - '3000:3000'
    # healthcheck:
    #   test: curl --fail http://localhost:8000/ping || exit 1
    #   interval: 5s
    #   timeout: 3s
    #   retries: 3
    networks:
      - net
    env_file:
      - .env

networks:
  net:
    driver: bridge
